app_advert:
    resource: "@AppBundle/Controller/AdvertController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

KrumoBundle:
    resource: "@MjmKrumoBundle/Resources/config/routing/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

linkedin_login:
    path: /login/check-linkedin