# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email    
        hwi:                               
            id: hwi_oauth.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false

        main:
            pattern: ^/
            form_login:
                provider:               fos_userbundle
                csrf_token_generator:   security.csrf.token_manager
                login_path:             homepage
                use_forward:            false
                check_path:             fos_user_security_check
                failure_path:           null
                default_target_path:    homepage
                require_previous_session: false
                remember_me:            true
            remember_me:
                secret:        %secret%
                lifetime:   31536000  # 365 days in seconds
                path:       /
                domain:     ~
            logout:
                path:       fos_user_security_logout
                target:     homepage
            anonymous:      true
            switch_user:    true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    linkedin:           "/login/check-linkedin"       
                login_path:        homepage
                use_forward:       false
                failure_path:      null
                oauth_user_provider:
                    service: my_user_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }