# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     my_user_provider.class: UserBundle\Security\Core\User\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, linkedin: linkedin_id}]
    app.form.advert:
        class: AppBundle\Form\AdvertType
        tags:
            - { name: form.type, alias: app_user_advert }
    user_rolechecker:
        class: UserBundle\RoleChecker\RoleChecker
        arguments: [@security.role_hierarchy]
    acme.demobundle.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
        arguments: ['@doctrine.orm.entity_manager']
