<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	public function getAdvertsForSearch($string){
		$result = $this->getEntityManager()
				->createQuery('SELECT a FROM AppBundle:Advert a  WHERE a.title LIKE :string OR a.content LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
        return $result;
	}

    public function getAdvertsByCategory($categoryId, $isAdvertIndex = false) {
        if(!is_array($categoryId))
        {
            if ($isAdvertIndex == false)
            {
                $result = $this->getEntityManager()
                    ->createQuery("SELECT a from AppBundle:Advert a LEFT JOIN a.category c with c.id = :categoryId where a.category = c.id")
                    ->setParameter("categoryId", $categoryId)
                    ->getResult();
            }
            else
            {
                $result = $this->getEntityManager()
                    ->createQuery("SELECT a from AppBundle:Advert a LEFT JOIN a.category c with c.id = :categoryId where a.category = c.id order by a.updatedAt DESC")
                    ->setParameter("categoryId", $categoryId)
                    ->getResult();
            }
        }
        else 
        {   
            $result = $this->getEntityManager()
                ->createQuery("SELECT a from AppBundle:Advert a LEFT JOIN a.category c  WHERE a.category = c.id AND a.category IN (:categoryId) order by a.updatedAt DESC")
                ->setParameter("categoryId", implode(',', $categoryId["filtre"]))
                ->getResult();
        }

        return $result;
    }
}
